### ISSUE TITLE
Font Awesome

### ISSUE THREAD

**Issue by joeyouss** [joeyouss/Felicity#1]
Add icons to the following class-
1. feature-box (the names- check-circle, bullseye, heart)
2. for button- (use any icon relevant to both the buttons)

**Comment by Harshith2255** [comment]
Hi
I would like to contribute to this project.

**Comment by joeyouss** [comment]
> Hi
> I would like to contribute to this project.

Sure ! Go ahead

**Comment by Harshith2255** [comment]
could you tell me where i have to add icons?

**Comment by joeyouss** [comment]
Hi! One needs to be added in github repository card and every other card. You can find them with class "card" and put appropriate icons. For github one, i would prefer the github icon placed. Thanks!
