### ISSUE TITLE
Create web page for book recommendations

### ISSUE THREAD

**Issue by joeyouss** [joeyouss/Felicity#13]
The specifications:
1. make a structure (preferred div) for books. Don't fill book names or summary.
2. Link to good reads for more books.

The page needs to be built from scratch

**Comment by mamadou-diallo** [comment]
Could you provide more information on what you're looking for? your specification is a bit vague.

**Comment by joeyouss** [comment]
@mamadou-diallo if you check the website or click on netlify, there is a section for books. It says "want a long read". This button when clicked would lead to the books html page which hasn't been created yet. The issue is explanatory as to what that page should contain.
Thank you !
