### ISSUE TITLE
Favicon Required

### ISSUE THREAD

**Issue by DivyanshSareen** [joeyouss/Felicity#7]
The website needs a favicon. Feel free to give your suggestions!
![image](https://user-images.githubusercontent.com/59335572/101249573-4da61a80-3743-11eb-9518-72e8dccc18dc.png)

**Comment by IvanL24** [comment]
hello, I'm interested with this issue, can I have it?

**Comment by DivyanshSareen** [comment]
Hello @IvanL24 , 
Thanks for showing interest in our project. We just saw your commit b792a18. It would be great if you can show us a preview of the favicon here.
